before_script:
    -  sed -i '/^#\sdeb-src /s/^#//' '/etc/apt/sources.list'
    - apt-get update && apt-get build-dep --yes geoclue-2.0
    - apt-get install --yes git gobject-introspection libmm-glib-dev wget libnotify-dev xsltproc gtk-doc-tools gettext modemmanager-dev

# Ubuntu 14.04 is not supported, see README for details

ubuntu-16.04:
    image: ubuntu:xenial
    script: ./autogen.sh --disable-nmea-source && make -j && make -j check && make install

ubuntu-17.10:
    image: ubuntu:artful
    script: ./autogen.sh --disable-nmea-source && make -j && make -j check && make install

ubuntu-18.04:
    image: ubuntu:bionic
    script: ./autogen.sh --disable-nmea-source && make -j && make -j check && make install
