before_script:
    -  sed -i '/^#\sdeb-src /s/^#//' '/etc/apt/sources.list'
    - apt-get update && apt-get build-dep --yes geoclue-2.0
    - apt-get install --yes git gobject-introspection libmm-glib-dev wget libnotify-dev xsltproc gtk-doc-tools python3-pip ninja-build gettext modemmanager-dev
    - pip3 install meson

# Ubuntu 14.04 is not supported, see README for details
#
# FIXME: Also disable gtk-doc on Ubuntu 16.04 cause it fails install. Would be nice to get it fixed.

ubuntu-16.04:
    image: ubuntu:xenial
    script: meson -Dnmea-source=false -Dgtk-doc=false build && ninja -C build && ninja -C build test && ninja -C build install

ubuntu-17.10:
    image: ubuntu:artful
    script: meson -Dnmea-source=false build && ninja -C build && ninja -C build test && ninja -C build install

ubuntu-18.04:
    image: ubuntu:bionic
    script: meson -Dnmea-source=false build && ninja -C build && ninja -C build test && ninja -C build install
